version: '2.3'

x-volumes:
  &default-volumes
    volumes:
      - files:/app/web/sites/default/files
      - ./:/app/web/profiles/contrib/govcms:delegated

x-environment:
  &default-environment
    LAGOON_ROUTE: ${LOCALDEV_URL:-http://govcms9.docker.amazee.io}

volumes:
  files: {}

services:

  cli: # cli container, will be used for executing composer and any local commands (drush, drupal, etc.)
    image: ${DOCKERHUB_NAMESPACE:-govcms}/${GOVCMS_CLI_IMAGE_NAME:-govcms}:${GOVCMS_IMAGE_TAG:-latest}
    << : *default-volumes # loads the defined volumes from the top
    environment:
      << : *default-environment

  test:
    image: ${DOCKERHUB_NAMESPACE:-govcms}/${GOVCMS_IMAGE_TEST_IMAGE_NAME:-test}:${GOVCMS_IMAGE_TAG:-latest}
    << : *default-volumes
    depends_on:
      - cli
    environment:
      << : *default-environment

  nginx:
    image: ${DOCKERHUB_NAMESPACE:-govcms}/nginx-drupal:${GOVCMS_IMAGE_TAG:-latest}
    << : *default-volumes
    environment:
      << : *default-environment
    networks:
      - amazeeio-network
      - default

  php:
    image: ${DOCKERHUB_NAMESPACE:-govcms}/php:${GOVCMS_IMAGE_TAG:-latest}
    << : *default-volumes
    environment:
      << : *default-environment

  mariadb:
    image: ${DOCKERHUB_NAMESPACE:-govcms}/mariadb-drupal:${GOVCMS_IMAGE_TAG:-latest}
    ports:
      - "3306" # Find port on host with `docker-compose port mariadb 3306`
    environment:
      << : *default-environment

  solr:
    image: ${DOCKERHUB_NAMESPACE:-govcms}/solr:${GOVCMS_IMAGE_TAG:-latest}
    ports:
      - "8983" # Find port on host with `docker-compose port solr 8983`
    environment:
      << : *default-environment

  chrome:
    image: ${DOCKERHUB_NAMESPACE:-govcms}/chrome:${GOVCMS_IMAGE_TAG:-latest}
    shm_size: '1gb'
    depends_on:
      - test
    << : *default-volumes

networks:
  amazeeio-network:
    external: true
